# docker/docker-compose.yml
version: '3.8'

services:
  # 🗄️ PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: vpn_bot_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-xui_bot_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vpn_bot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🤖 Telegram бот
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vpn_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      # База данных
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-xui_bot_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      # 3x-ui настройки
      - XUI_PANEL_URL=${XUI_PANEL_URL}
      - XUI_USERNAME=${XUI_USERNAME}
      - XUI_PASSWORD=${XUI_PASSWORD}
      - INBOUND_ID=${INBOUND_ID:-1}
      - XUI_EXTERNAL_IP=${XUI_EXTERNAL_IP}
      # Дополнительные настройки
      - COLLECT_EMAIL=${COLLECT_EMAIL:-false}
      - COLLECT_PHONE=${COLLECT_PHONE:-false}
      - PAYMENT_ENABLED=${PAYMENT_ENABLED:-false}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vpn_bot_network
    volumes:
      - qrcodes_volume:/app/qrcodes
    # Для разработки - монтируем код
    # volumes:
    #   - ../handlers:/app/handlers
    #   - ../services:/app/services
    #   - ../main.py:/app/main.py
    #   - ../config.py:/app/config.py

  # 📊 Adminer для управления БД (опционально)
  adminer:
    image: adminer
    container_name: vpn_bot_adminer
    ports:
      - "8080:8080"
    networks:
      - vpn_bot_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  qrcodes_volume:
    driver: local

networks:
  vpn_bot_network:
    driver: bridge